# Generated by Django 2.0.1 on 2018-01-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Created_Date',
            new_name='created_Date',
        ),
    ]
